
services:
  frontend:
    image: ${WEBAPP_IMAGE}
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
  backend:
    image: ${API_IMAGE}
    ports:
      - "4040:4040"
    env_file:
      - .env
    restart: always   
