
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: always
  api:
    image: ${API_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always   