
services:
  webapp:
    build:
      context: ./frontend
    ports:
      - '3001:3000'
    volumes:
      - './frontend:/opt/app'
    environment:
      - "CI:'true'"
    restart: always
  api:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/opt/app'
    restart: always