
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: always
  api:
    image: ${API_IMAGE}
    ports:
      - "5000:4040"
    env_file:
      - .env
    restart: always   
